In [2]:
import random

import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

## 1. Data Types and Attributes

In [4]:
## main data type is nd array (number of dimensions / N-dimensional array)
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

## 2. Creating Arrays

In [8]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
ones.dtype

dtype('float64')

In [10]:
zeroes = np.zeros((2, 3))

In [11]:
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
range_array = np.arange(0, 12, 3) ## range is 0 --> 12 and this steps up by 3 so 0+3 the next time.
range_array

array([0, 3, 6, 9])

In [17]:
random_array = np.random.randint(0, 10, size=(3,5)) ## prints random values of 0, 10 and the array will be of size=(3, 5);
random_array

array([[8, 2, 6, 2, 0],
       [6, 6, 3, 2, 5],
       [1, 9, 5, 1, 9]])

In [19]:
random_array2 = np.random.random((4, 5))
random_array2

array([[0.6083198 , 0.52534332, 0.23656904, 0.26393402, 0.32934172],
       [0.47530624, 0.1567779 , 0.16559638, 0.90990528, 0.70603815],
       [0.53641222, 0.34951397, 0.13763338, 0.39387746, 0.7648078 ],
       [0.41084683, 0.47840788, 0.65045181, 0.19172399, 0.09836089]])

In [31]:
## Pseudo random numbers
np.random.seed(seed=0) #seed says to numpy that not generate random numbers but not to change them

random_array

array([[8, 2, 6, 2, 0],
       [6, 6, 3, 2, 5],
       [1, 9, 5, 1, 9]])

## 3. Viewing Arrays and Matrices

In [32]:
random_array[:1, :1]

array([[8]])

## 4. Manipulating and Comparing Arrays

# Arithmetic

In [33]:
a1

array([1, 2, 3])

In [34]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [35]:
a1 + ones

array([2., 3., 4.])

In [36]:
a1 - ones

array([0., 1., 2.])

In [37]:
a1*ones

array([1., 2., 3.])

In [39]:
a2 = np.array([[1, 2, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [40]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [41]:
a2 // a1 ## Floor division removes the decimals (rounds down)

array([[1., 1., 1.],
       [4., 2., 2.]])

In [42]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [43]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

## 5. Aggregation

Performing the same operation on a number of things

In [44]:
a1

array([1, 2, 3])

In [45]:
massive_array = np.random.random(100000)
massive_array

array([0.5488135 , 0.71518937, 0.60276338, ..., 0.81013284, 0.55103228,
       0.22575586])

In [46]:
massive_array[:10]

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [47]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

15.3 ms ± 236 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
30.9 µs ± 247 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Standard deviation and variance

In [48]:
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [49]:
np.var(high_var_array), np.var(low_var_array)
#varience is average degree to which each number is different to the mean
#higher variance = wider range of numbers
#lower variance = lower range of numbers
np.var(a2)

(4296133.472222221, 8.0)

In [50]:
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

## 6. Reshaping and Transposing

In [52]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [53]:
a2.shape

(2, 3)

In [61]:
a3 = pd.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],

               [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [62]:
a3.shape

(2,)

In [63]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [65]:
reshape = a2.reshape(2, 3, 1)

(2, 3, 1)

In [66]:
a3.shape

(2,)

In [69]:
reshape * a3

NameError: name 'reshape' is not defined

In [71]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

## 7. Matrix Multiplication

In [72]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

In [73]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [74]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [75]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [76]:
mat2*mat1

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [77]:
#Dot product
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [78]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [79]:
mat1.T.shape

(3, 5)

In [80]:
mat3 = np.dot(mat1, mat2.T)

In [81]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## 8. Comparison operator

In [82]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [83]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [85]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

## 9. Sorting Arrays

In [86]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[8, 2, 6, 2, 0],
       [6, 6, 3, 2, 5],
       [1, 9, 5, 1, 9]])

In [87]:
random_array.shape

(3, 5)

In [88]:
np.sort(random_array)

array([[0, 2, 2, 6, 8],
       [2, 3, 5, 6, 6],
       [1, 1, 5, 9, 9]])

In [89]:
np.argsort(random_array) ## Returns the indices that would sort an array
## 6 has got address 4, (first row)

array([[4, 1, 3, 2, 0],
       [3, 2, 4, 0, 1],
       [0, 3, 2, 1, 4]], dtype=int64)

In [90]:
np.argmax(a1)

2

In [91]:
np.argmin(a1)

0

In [92]:
random_array

array([[8, 2, 6, 2, 0],
       [6, 6, 3, 2, 5],
       [1, 9, 5, 1, 9]])

In [93]:
np.argmax(random_array)

11

In [94]:
np.argmax(random_array, axis=0)

array([0, 2, 0, 0, 2], dtype=int64)

In [95]:
np.argmax(random_array, axis=1)

array([0, 0, 1], dtype=int64)

## 10. Practical Examples

In [97]:
## Turn an image into a NumPy array
from matplotlib.image import imread
panda  = imread("panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [98]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [99]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [101]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

In [102]:
car = imread("car-photo.png")

In [103]:
print(type(car))

<class 'numpy.ndarray'>


In [107]:
dog = imread("dog-photo.png")
print(type(dog))

<class 'numpy.ndarray'>


## The End